### ISSUE TITLE
yolov11n_- visdrone.pt

### ISSUE THREAD

**Issue by thalapandi** [SamruddhiBande/Parking_Management_System#2]

**Comment by SamruddhiBande** [comment]
Hi Pandian,

Thank you for your question! Regarding compatibility with DeepStream 7.0, the YOLOv11 model you've mentioned would need to be converted into the TensorRT format for full compatibility. DeepStream 7.0 works best with models in TensorRT (.engine) format, which is optimized for NVIDIA GPUs.

Conversion Process:
Export the YOLOv11 model to ONNX: You can start by exporting the PyTorch .pt model to ONNX format using:
import torch
model = torch.load('yolov11.pt')
torch.onnx.export(model, dummy_input, "yolov11.onnx", verbose=True)


Convert ONNX to TensorRT: After obtaining the ONNX model, you can convert it to TensorRT using NVIDIA's TensorRT toolkit. This will allow the model to be optimized for inference in DeepStream.

Example conversion using trtexec:

trtexec --onnx=yolov11.onnx --saveEngine=yolov11.engine


DeepStream Configuration: Once the model is in TensorRT format, you can use it in DeepStream by adjusting input sizes and other configurations to match the specific needs of your application.

I hope this helps! If you need further assistance with the conversion or DeepStream setup, feel free to reach out.

Best regards,
Samruddhi

**Comment by thalapandi** [comment]
Thank you so much for your response! I'll test it on my Jetson AGX Orin
Nano, and I'll let you know if it works.

**Comment by SamruddhiBande** [comment]
Yes that'd be great!
